name: PlatformIO Dependabot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: run PlatformIO Dependabot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run PlatformIO Dependabot
        uses: peterus/platformio_dependabot@v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
