name: PlatformIO Build and Release

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1.1.2
        with:
          environments: "esp32dev"
          project-conf: "./platformio.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .pio/build/*
            data/*
            include/*
            lib/*
            src/*
            no_ota.csv
            platformio.ini
            Release.txt
            LICENSE