name: PlatformIO

on: 
    - pull_request
    - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PlatformIO Run
        uses: infra-blue/platformio-run-action@v1.1.3
        with:
          environments: "esp32dev"
          project-conf: "./platformio.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false